apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: main-issuer
  namespace: cert-manager
spec:
  acme:
    email: email@email.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: digitalocean-key
    solvers:
      - dns01:
          digitalocean:
            tokenSecretRef:
              name: digitalocean-dns
              key: access-token
