apiVersion: v1
kind: Secret
metadata:
  name: github-registry-secret
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "ghcr.io": {
          "username": "bitforger",
          "password": "{{ op://HomeLab Secrets/GitHub Registry Secret/password }}",
          "email": "{{ op://HomeLab Secrets/GitHub Registry Secret/email }}",
          "auth": "{{ op://HomeLab Secrets/GitHub Registry Secret/auth }}"
        }
      }
    }
