config:
  watchPlugins: true
pluginsManager:
  enabled: true
  configContent: |
    plugins: []
    installOptions:
      parallel: true
      maxConcurrent: 2
  baseImage: node:lts-alpine
  version: latest

ingress:
  enabled: true
  ingressClassName: traefik-external
  hosts:
    - host: headlamp.bitforger.dev
      paths:
        - path: /
          type: Prefix
  tls:
    - secretName: headlamp-tls
      hosts:
        - headlamp.bitforger.dev
  annotations:
    cert-manager.io/issuer: main-issuer
    cert-manager.io/issuer-kind: ClusterIssuer
    # Optional: Force SSL redirect if not handled globally by Traefik
    # traefik.ingress.kubernetes.io/router.tls: "true"

service:
  type: ClusterIP
